---
title: "Lab 1"
author: "Andrew Holzwarth"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Research Questions
  # Are ppg and minutes played related between certain players or on a league level?
```


```{r}
# import data
df <- read.csv('/Users/andrewholzwarth/Desktop/DS 3001/ASA Heat Check Data (2).csv')

# install pachages
library(tidyverse)
```

```{r}
#Clean Data

#Remove unecessecary columns
df1 <- df[,c(5,22:24,26:34,43,63)]
df1$starter <- as.factor(df1$starter)

#Create another dataset with League Average (each person only has 1 row)
league <- df1 %>%
  group_by(player, Team_Abbrev, starter) %>%
  summarize(fg3 = mean(fg3),
            fg3a = mean(fg3a),
            fg3_pct = fg3/fg3a,
            pts = mean(pts),
            minutes = mean(minutes))

na.omit(league) #Gets rid of players with 0 3 point attempts bc 0/0 = NA


#Players data frames
player_Lebron <- df1[which(df$player_id == "jamesle01"),]
player_Durant <- df1[which(df$player_id == "duranke01"),]
player_Young <- df1[which(df$player_id == "youngtr01"),]
player_Griffin <- df1[which(df$player_id == "griffbl01"),]
player_Tatum <- df1[which(df$player_id == "tatumja01"),]
player_Curry <- df1[which(df$player_id == "curryst01"),]





```

```{r}
#Plot the Data

#League
ggplot(league, aes(x = fg3_pct, y = minutes, shape = starter, color = Team_Abbrev ))+
  geom_point(size = 5, alpha = .75)+
  theme_bw()+
  labs(title = "NBA League", subtitle = "By Player")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")
  
  
  
  

#LeBron James
mid <- mean(player_Lebron$pts)
ggplot(player_Lebron, aes(x = fg3_pct, y = minutes))+
  geom_point(aes(color = pts), size = 5, alpha = .75)+
  scale_color_gradient2(midpoint = mid, low = 'blue', mid = 'grey', high = 'red')+
  theme_bw()+
  geom_smooth(method="lm", se = FALSE, color = 'black')+
  labs(title = "Lebron James")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")

#Kevin Durant
mid <- mean(player_Durant$pts)
ggplot(player_Durant, aes(x = fg3_pct, y = minutes))+
  geom_point(aes(color = pts), size = 5, alpha = .75)+
  scale_color_gradient2(midpoint = mid, low = 'blue', mid = 'grey', high = 'red')+
  theme_bw()+
  geom_smooth(method="lm", se = FALSE, color = 'black')+
  labs(title = "Kevin Durant")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")

#Trae Young
mid <- mean(player_Young$pts)
ggplot(player_Young, aes(x = fg3_pct, y = minutes))+
  geom_point(aes(color = pts), size = 5, alpha = .75)+
  scale_color_gradient2(midpoint = mid, low = 'blue', mid = 'grey', high = 'red')+
  theme_bw()+
  geom_smooth(method="lm", se = FALSE, color = 'black')+
  labs(title = "Trae Young")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")

#Blake Griffin
mid <- mean(player_Griffin$pts)
ggplot(player_Griffin, aes(x = fg3_pct, y = minutes))+
  geom_point(aes(color = pts), size = 5, alpha = .75)+
  scale_color_gradient2(midpoint = mid, low = 'blue', mid = 'grey', high = 'red')+
  theme_bw()+
  geom_smooth(method="lm", se = FALSE, color = 'black')+
  labs(title = "Blake Griffin")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")

#Jason Tatum
mid <- mean(player_Tatum$pts)
ggplot(player_Tatum, aes(x = fg3_pct, y = minutes))+
  geom_point(aes(color = pts), size = 5, alpha = .75)+
  scale_color_gradient2(midpoint = mid, low = 'blue', mid = 'grey', high = 'red')+
  theme_bw()+
  geom_smooth(method="lm", se = FALSE, color = 'black')+
  labs(title = "Jason Tatum")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")

#Steph Curry
mid <- mean(player_Curry$pts)
ggplot(player_Curry, aes(x = fg3_pct, y = minutes))+
  geom_point(aes(color = pts), size = 5, alpha = .75)+
  scale_color_gradient2(midpoint = mid, low = 'blue', mid = 'grey', high = 'red')+
  theme_bw()+
  geom_smooth(method="lm", se = FALSE, color = 'black')+
  labs(title = "Steph Curry")+
  xlab("3 Point Percentage")+
  ylab("Minutes per Game")
```








