---
title: 'Programming Lab #3'
author: "DS 3001: Introduction to Machine Learning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(tidyverse)
library(tidyr)
library(purrr)
library(broom)
library(clue)
library(class)
```
Andrew Holzwarth, Brian Bippert, Felipe Martinez, Garrett Burroughs, Tyler Lynch  

## Summary
The goal of this lab was to gerrymander two sets of voting districts in Virginia. One in favor of the **Republican** Party and another in favor of the **Democratic** party. The idea of gerrymandering a state is simple: create districts that create an artificial majority in favor of one political party over another. However, the problem is very difficult to solve with concessions being made at different steps that can drastically change the outcome of the problem, such as keeping districts contiguous and of similar population sizes. Some of the concessions made for our lab was only grouping districts along county lines instead of being more granular and making a simple prediction model based on averages of the past 20 years instead of using a more complex model that puts more weight on recent years.  
	To tackle the problem, our group created a prediction model using `R` and used `Python` to create the contiguous and roughly equal-sized districts. The prediction model with `R` took the sum of how many votes each party received from 2000-2020. Whichever party received the most votes was deemed to be the political leaning of that specific county. The districting algorithm utilized the adjacency matrix of all counties in Virginia. The algorithm begins by selecting 11 **random** seed counties, and chooses to add to the district with the current smallest population. If there are no valid counties to add to the district with the smallest population, a county will *flip*. Flipping is a process that chooses a random county in the current district, and checks its neighbors. If a neighbor is valid to flip, it is moved from the district it is presently in to the district with the smallest population. The requirements for a valid flip are that the county to be flipped must not be in the district it is going to be flipped to and that removing that county from its current district does not break the continuity. If a district has no valid flips, a county is added to a random district, breaking the rule that the smallest district gets added to. This constraint is the main problem with this algorithm as the districts are only roughly equal, with some being significantly larger.  
	The results of our lab are not perfect gerrymandered districts of Virginia, but they do create 11 relatively equal districts. Our code also only makes one random set of districts without caring about the political leaning, but it does output which party won and the ratio of districts that lean toward each party. With more work by students in future semesters, we believe that our project would be a great jumping off point for them to make perfectly gerrymandered districts in Virginia.  

***

## Data
The three datasets that we used for the assignment were `voting_VA.csv`, `countrypres_2000-2020.csv`, and a file that specified which counties were adjacent to each other. The predictive model used the `voting_VA` file to compute the winning party per county. 

* `voting_VA.csv` - A dataframe that includes data on voting data from 2000-2022, every state, all counties, county FIPS codes, candidates, political parties, and how many votes each candidate and party got each year. The prediction model used the ratio of *candidate votes* to determine which party won each county throughout the past **6** election cycles. The data had to be wrangled to include only Virginia, one line per county instead of 3-5 depending on which parties were on the poll, and to calculate which party received the greatest share of votes within each county. The newly wrangled data frame is called `df_flipped` and was then used in conjunction with `county_adjacendies.csv` to create the districts. We had no issues wrangling the data for the prediction model.  
  + `year`: The election year
  + `state`: The specific state within the United States that row pertains to 
  + `county_name`: The county name for that specific row within a specific state
  + `county_fips`: The FIPS code for the county, which is a number to uniquely identify a geographical location/area
  + `party`: The political party for that specific row
  + `candidatevotes`: How many votes that party/candidate got within 1 county for 1 election year
  + `totalvotes`: The total number of votes within 1 county for 1 election year
* `county_adjacencies.csv` - an adjacency list of all counties in Virginia. This file was the backbone of the districting algorithm. There were some small issues with this file, including some counties existing as a neighbor to a different county, but not vice versa. Other issues included some small misspellings or counties existing twice within a single row of the adjacency list. All of these issues were found and changed while running the districting code as it would return an error if it came across any discrepancies in the file. Any mistakes currently in the file do not impact the end result of our work, but may need to be addressed in future iterations of the project.


***

## Results
  For our prediction model, the process is very binary with each county being classified as either `democrat` or `republican` regardless of the discrepancy in votes between each party. Although our prediction model works and does not omit any county, there are areas to make the model more sophisticated. Using percentages of votes between the two parties, and therefore keeping track of counties with large percentages of votes within each county, we could make a model that is not binary, but rather characterizes the political leaning of each county along a scale. More extreme values would be binary in nature, but some counties would have “**average**” values which show a more even split of political leanings. Additionally, we could put more weight on recent elections to show how Virginia is changing over time compared to characterizing 2000 data the same as 2020 data. With more time and knowledge the model could become more sophisticated and show closer to a true prediction of voting patterns.  
  Our process for gerrymandering involved generating a random apportionment of Virginia into 11 contiguous and roughly equal districts and then summing the population of each district where the sign of each county was determined by the predicted voting outcome. Essentially, if a county was predicted to vote **Democrat**, their population would be multiplied by `-1`. Then all populations would be added across a district. If this sum is **negative**, there were more votes for the Democrats. This district would then be added to the Democrats total districts. Whichever party wins more districts would then win Virginia. This model only accounts for who wins a district, which overlooks close districts that tend to average around 50% per major party. In these cases, updating the predictive model to return a percentage of the county that will vote a certain way would drastically increase the accuracy of our results. Another change that can be made is to account for the current trend of each county. Our current predictive model just looks at overall totals, but by more heavily weighting recent voting trends, our predictive model may improve in accuracy. Another drawback of the gerrymandering function is that we cannot specify 11 districts in either party’s favor. The districts are going to be **random** for every output, but we will receive a statement showing which party will win the most districts and the margin of victory.
 

***

## Conclusion
  At a baseline level, gerrymandering voting districts appears to be a simple assignment, but the biggest challenge was creating the voting districts. Building the prediction model to see which party each county votes for was time consuming, but not challenging. We were only able to create districts using `python`, which although was not restricted, was not the language that we used for machine learning during the semester.  
	As stated in the introduction, although our code does create districts that give preferences towards both parties, the districts are not perfect and could be perfected by students in future semesters. The algorithm provided contains key functions that will be useful in future projects, such as the `flip` function, which flips a county to a different district. If we had chosen to start with predefined counties, this function would have been very valuable at generating new and gerrymandered districts. However, we wanted to be more ambitious, building the voting districts from scratch, which required a lot more overhead as adding to a district is significantly more difficult than just reshuffling already existing districts. Despite the issues, we are very pleased with the results of our project as each run of our code produces a unique districting and therefore unique voting map of Virginia. Although the population constraint got somewhat lost, all districts are contiguous. This problem can be solved in future research by splitting the higher populated counties into smaller chunks, preventing the counties in Northern Virginia from dominating. Furthermore, the districting algorithm can absolutely be improved. It currently chooses to add to a district based on the population count of a district, which can be modified to account for the political leaning of that district as well. This would move the project over from producing random districts to producing the most optimal gerrymandering given the initial 11 seed counties. We feel that this is the most significant improvement that can be made to our project.  
Although these changes would improve the results of the project, they were not easily feasible for us at this time with the tools available. Despite our time and knowledge constraints, students doing this project in the future will find that our work is a very helpful starting point, providing a baseline for improvement. Similarly we find that our project accomplishes what we set out to do, create a gerrymandered Virginia. A key portion of our functionality is that the best result our code can produce is a result of how many times you run it, which is the only way to find the best solution to an NP-hard problem like this one. However, there is no true “best” gerrymandering. All voting models are predictive, populations change, world events and politicians and money all impact how and why people vote. The best any possible gerrymandering can do is an approximation, which is what we accomplished.  
